### ISSUE TITLE
Go up / down page does not work

### ISSUE THREAD

**Issue by vip9** [smoothgesturesplus/Issues#55]
Linux, chrome 61.0.3163.39  beta (64-bit), go up/down with gesture or right mouse button+wheel up/down does not work

**Comment by smoothgesturesplus** [comment]
This is fixed in 2.8, which is being released today. Thanks for the report.

**Comment by smoothgesturesplus** [comment]
There are some more related issues.

**Comment by mochakaboom** [comment]
Yea I'm having trouble with mouse gesture up/down to go to the top/bottom of the page.  I'm on 2.8 also and it's still happening =/

**Comment by smoothgesturesplus** [comment]
Alright, I expect 2.8.1 to fix the remaining issue. Please let me know if you experience it again. Thanks!

**Comment by mochakaboom** [comment]
Thank you, fixed now
